language: go
go:
  - 1.6
before_install:
  - echo $SERVICE_KEY > service_key.json
install:
  - go get golang.org/x/net/context
  - go get golang.org/x/oauth2/google
  - go get google.golang.org/api/calendar/v3
script:
  - go run main.go
